gitSourceBranch = "main"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

classOrder = [
    "utility",
    "Countdown",
    "Queue",
    "Meter",
    "Tracker"
]

apiCategories = [
    "Instance Function",
    "Table Function",
    "Radius Function",
    "Event Function"
]