gitSourceBranch = "main"

classOrder = [
    "utility",
    "Countdown",
    "Queue",
    "Meter",
    "Tracker"
]

apiCategories = [
    "Instance Function",
    "Table Function",
    "Radius Function",
    "Event Function"
]

[home]
enabled = true
includeReadme = true # Optional

[[home.features]]
title = "The Utility Functions"
description = "UtilityModule comes with a bunch of function that make certain situations easier!"
image = ""