title = "UtilityModule"
gitRepoUrl = "https://github.com/denispionicul/UtilityModule"

gitSourceBranch = "main"

classOrder = [
    "utility",
    "Countdown",
    "Queue",
    "Meter",
    "Tracker"
]

apiCategories = [
    "Instance Function",
    "Table Function",
    "Radius Function",
    "Event Function"
]