gitSourceBranch = "main"

classOrder = [
    "utility",
    "Countdown",
    "Queue",
    "Meter",
    "Tracker"
]

apiCategories = [
    "Instance Function",
    "Table Function",
    "Radius Function",
    "Event Function"
]

[home]
enabled = true
includeReadme = true # Optional

[[home.features]]
title = "API"
description = "Have a look at UtilityModule's API"
image = "https://denispionicul.github.io/UtilityModule/api/utility"