gitSourceBranch = "main"

classOrder = [
    "utility",
    "Countdown",
    "Queue",
    "Meter",
    "Tracker"
]

apiCategories = [
    "Instance Function",
    "Table Function",
    "Radius Function",
    "Event Function"
]

[home]
enabled = true
includeReadme = true # Optional