[package]
name = "denispionicul/UtilityModule"
description = "UtilityModule is a collections of useful functions and classes."
version = "1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.5.0"
Trove = "sleitnick/trove@0.5.0"  