name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check Code
      uses: actions/checkout@v3

    - uses: LPGhatguy/setup-aftman@v1
      name: Install Aftman
      with:
          version: "1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Lint
      run: 
        selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --check .      